version: '3'

services:
  api:
    build: .
    ports:
      - "8012:8012"
    volumes:
      - .:/app
      - ./course_data:/app/course_data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped