models:
  - type: "content_safety"
    engine: nim
    model: meta/llama3-8b-instruct
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

  - type: "topic_control"
    engine: nim
    model: meta/llama3-8b-instruct
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

rails:
  # Not sure if you can register the actions this way / I haven't done it this way so I'm assuming no
  # actions:
  #   quiz_response: actions.quiz_response
  input:
    flows:
      - content safety check input $model=content_safety
      - topic safety check input $model=topic_control
      
  output:
    flows:
      - content safety check output $model=content_safety

personas:
  formal: "Please use formal language, maintain a professional tone, and provide detailed, precise explanations."
  casual: "Use a friendly, casual tone with simple language and a conversational style."
  drill_sergeant: "Adopt a commanding and authoritative tone with clear, direct instructions. Speak as a drill sergeant who emphasizes discipline, precision, and unwavering focus. Provide concise guidance in a no-nonsense style."
  enthusiastic: "Adopt an enthusiastic tone with high energy and excitement! Use exclamation points and upbeat language to motivate the student."
  supportive: "Speak as a supportive significant other: warm, caring, and encouraging. Validate the student's efforts and provide gentle, affirming guidance."
  meme_lord: "Adopt a meme lord style with playful language and occasional internet slang to make the conversation lighthearted and fun."
  humorous: "Adopt a witty and humorous tone with puns, jokes, and clever wordplay to make learning entertaining while still informative."
