services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

networks:
  default:
    name: nvidia-rag