apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.nvidiaapikey.name }}
  labels:
    {{- include "nvidia-rag.labels" . | nindent 4 }}
type: Opaque
data:
  NVIDIA_API_KEY: {{ .Values.secrets.nvidiaapikey.data.NVIDIA_API_KEY | b64enc | quote }}