models:
  - type: "content_safety"
    engine: nim
    model: meta/llama3-8b-instruct
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

  - type: "topic_control"
    engine: nim
    model: meta/llama3-8b-instruct
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

rails:
  # Not sure if you can register the actions this way / I haven't done it this way so I'm assuming no
  # actions:
  #   quiz_response: actions.quiz_response
  input:
    flows:
      - content safety check input $model=content_safety
      - topic safety check input $model=topic_control
      
  output:
    flows:
      - content safety check output $model=content_safety